/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : string,
  'content' : string,
  'role' : string,
  'timestamp' : bigint,
  'toolUsed' : string,
}
export interface FantasySuggestion {
  'captainName' : string,
  'viceCaptainId' : string,
  'reasoning' : string,
  'viceCaptainName' : string,
  'matchId' : string,
  'totalCredits' : bigint,
  'suggestedPlayers' : Array<[string, string]>,
  'captainId' : string,
}
export interface Match {
  'id' : string,
  'status' : MatchStatus,
  'venue' : string,
  'homeTeam' : string,
  'sport' : Sport,
  'homeScore' : bigint,
  'awayTeam' : string,
  'awayScore' : bigint,
  'matchDate' : Time,
}
export interface MatchPrediction {
  'keyFactors' : string,
  'predictedScore' : string,
  'matchId' : string,
  'awayWinProbability' : bigint,
  'confidence' : PredictionConfidence,
  'homeWinProbability' : bigint,
  'drawProbability' : bigint,
}
export type MatchStatus = { 'upcoming' : null } |
  { 'live' : null } |
  { 'completed' : null };
export interface MatchSummary {
  'generatedAt' : Time,
  'highlights' : Array<string>,
  'summary' : string,
  'matchId' : string,
  'keyMoments' : string,
}
export interface MotivationalQuote {
  'id' : string,
  'quoteText' : string,
  'author' : string,
  'category' : string,
}
export interface NewsArticle {
  'id' : string,
  'title' : string,
  'content' : string,
  'publishedAt' : Time,
  'author' : string,
  'sport' : Sport,
  'imageUrl' : string,
}
export interface Notification {
  'id' : string,
  'title' : string,
  'notificationType' : string,
  'createdAt' : Time,
  'sport' : Sport,
  'matchId' : string,
  'message' : string,
}
export interface Player {
  'id' : string,
  'name' : string,
  'team' : string,
  'sport' : Sport,
  'stats' : PlayerStats,
  'imageUrl' : string,
  'position' : string,
}
export interface PlayerStats {
  'recentForm' : Array<bigint>,
  'average' : number,
  'matchesPlayed' : bigint,
  'runsGoalsPoints' : bigint,
}
export type PredictionConfidence = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type Sport = { 'basketball' : null } |
  { 'football' : null } |
  { 'cricket' : null } |
  { 'tennis' : null } |
  { 'kabaddi' : null };
export type Time = bigint;
export interface UserProfile {
  'favoriteSport' : [] | [Sport],
  'name' : string,
  'favoriteTeam' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addQuote' : ActorMethod<[MotivationalQuote], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearChatHistory' : ActorMethod<[], undefined>,
  'createFantasySuggestion' : ActorMethod<[FantasySuggestion], undefined>,
  'createMatch' : ActorMethod<[Match], undefined>,
  'createNews' : ActorMethod<[NewsArticle], undefined>,
  'createNotification' : ActorMethod<[Notification], undefined>,
  'createPlayer' : ActorMethod<[Player], undefined>,
  'createPrediction' : ActorMethod<[MatchPrediction], undefined>,
  'createSummary' : ActorMethod<[MatchSummary], undefined>,
  'deleteMatch' : ActorMethod<[string], undefined>,
  'deleteNews' : ActorMethod<[string], undefined>,
  'getAllMatches' : ActorMethod<[], Array<Match>>,
  'getAllNews' : ActorMethod<[], Array<NewsArticle>>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getAllQuotes' : ActorMethod<[], Array<MotivationalQuote>>,
  'getCallerMessageCount' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getFantasySuggestionByMatchId' : ActorMethod<
    [string],
    [] | [FantasySuggestion]
  >,
  'getMatchesBySport' : ActorMethod<[Sport], Array<Match>>,
  'getMatchesByStatus' : ActorMethod<[MatchStatus], Array<Match>>,
  'getNewsBySport' : ActorMethod<[Sport], Array<NewsArticle>>,
  'getPlayersBySport' : ActorMethod<[Sport], Array<Player>>,
  'getPredictionByMatchId' : ActorMethod<[string], [] | [MatchPrediction]>,
  'getRecentNotifications' : ActorMethod<[], Array<Notification>>,
  'getSummaryByMatchId' : ActorMethod<[string], [] | [MatchSummary]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveChatMessage' : ActorMethod<[ChatMessage], undefined>,
  'updateFantasySuggestion' : ActorMethod<[FantasySuggestion], undefined>,
  'updateMatch' : ActorMethod<[Match], undefined>,
  'updateNews' : ActorMethod<[NewsArticle], undefined>,
  'updatePlayer' : ActorMethod<[Player], undefined>,
  'updatePrediction' : ActorMethod<[MatchPrediction], undefined>,
  'updateSummary' : ActorMethod<[MatchSummary], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];