/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FantasySuggestion = IDL.Record({
  'captainName' : IDL.Text,
  'viceCaptainId' : IDL.Text,
  'reasoning' : IDL.Text,
  'viceCaptainName' : IDL.Text,
  'matchId' : IDL.Text,
  'totalCredits' : IDL.Nat,
  'suggestedPlayers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'captainId' : IDL.Text,
});
export const MatchStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'live' : IDL.Null,
  'completed' : IDL.Null,
});
export const Sport = IDL.Variant({
  'basketball' : IDL.Null,
  'football' : IDL.Null,
  'cricket' : IDL.Null,
  'tennis' : IDL.Null,
  'kabaddi' : IDL.Null,
});
export const Time = IDL.Int;
export const Match = IDL.Record({
  'id' : IDL.Text,
  'status' : MatchStatus,
  'venue' : IDL.Text,
  'homeTeam' : IDL.Text,
  'sport' : Sport,
  'homeScore' : IDL.Nat,
  'awayTeam' : IDL.Text,
  'awayScore' : IDL.Nat,
  'matchDate' : Time,
});
export const NewsArticle = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishedAt' : Time,
  'author' : IDL.Text,
  'sport' : Sport,
  'imageUrl' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'notificationType' : IDL.Text,
  'createdAt' : Time,
  'sport' : Sport,
  'matchId' : IDL.Text,
  'message' : IDL.Text,
});
export const PlayerStats = IDL.Record({
  'recentForm' : IDL.Vec(IDL.Nat),
  'average' : IDL.Float64,
  'matchesPlayed' : IDL.Nat,
  'runsGoalsPoints' : IDL.Nat,
});
export const Player = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'team' : IDL.Text,
  'sport' : Sport,
  'stats' : PlayerStats,
  'imageUrl' : IDL.Text,
  'position' : IDL.Text,
});
export const PredictionConfidence = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const MatchPrediction = IDL.Record({
  'keyFactors' : IDL.Text,
  'predictedScore' : IDL.Text,
  'matchId' : IDL.Text,
  'awayWinProbability' : IDL.Nat,
  'confidence' : PredictionConfidence,
  'homeWinProbability' : IDL.Nat,
  'drawProbability' : IDL.Nat,
});
export const MatchSummary = IDL.Record({
  'generatedAt' : Time,
  'highlights' : IDL.Vec(IDL.Text),
  'summary' : IDL.Text,
  'matchId' : IDL.Text,
  'keyMoments' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'favoriteSport' : IDL.Opt(Sport),
  'name' : IDL.Text,
  'favoriteTeam' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFantasySuggestion' : IDL.Func([FantasySuggestion], [], []),
  'createMatch' : IDL.Func([Match], [], []),
  'createNews' : IDL.Func([NewsArticle], [], []),
  'createNotification' : IDL.Func([Notification], [], []),
  'createPlayer' : IDL.Func([Player], [], []),
  'createPrediction' : IDL.Func([MatchPrediction], [], []),
  'createSummary' : IDL.Func([MatchSummary], [], []),
  'deleteMatch' : IDL.Func([IDL.Text], [], []),
  'deleteNews' : IDL.Func([IDL.Text], [], []),
  'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getAllNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFantasySuggestionByMatchId' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(FantasySuggestion)],
      ['query'],
    ),
  'getMatchesBySport' : IDL.Func([Sport], [IDL.Vec(Match)], ['query']),
  'getMatchesByStatus' : IDL.Func([MatchStatus], [IDL.Vec(Match)], ['query']),
  'getNewsBySport' : IDL.Func([Sport], [IDL.Vec(NewsArticle)], ['query']),
  'getPlayersBySport' : IDL.Func([Sport], [IDL.Vec(Player)], ['query']),
  'getPredictionByMatchId' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MatchPrediction)],
      ['query'],
    ),
  'getRecentNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getSummaryByMatchId' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MatchSummary)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateFantasySuggestion' : IDL.Func([FantasySuggestion], [], []),
  'updateMatch' : IDL.Func([Match], [], []),
  'updateNews' : IDL.Func([NewsArticle], [], []),
  'updatePlayer' : IDL.Func([Player], [], []),
  'updatePrediction' : IDL.Func([MatchPrediction], [], []),
  'updateSummary' : IDL.Func([MatchSummary], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FantasySuggestion = IDL.Record({
    'captainName' : IDL.Text,
    'viceCaptainId' : IDL.Text,
    'reasoning' : IDL.Text,
    'viceCaptainName' : IDL.Text,
    'matchId' : IDL.Text,
    'totalCredits' : IDL.Nat,
    'suggestedPlayers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'captainId' : IDL.Text,
  });
  const MatchStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'live' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Sport = IDL.Variant({
    'basketball' : IDL.Null,
    'football' : IDL.Null,
    'cricket' : IDL.Null,
    'tennis' : IDL.Null,
    'kabaddi' : IDL.Null,
  });
  const Time = IDL.Int;
  const Match = IDL.Record({
    'id' : IDL.Text,
    'status' : MatchStatus,
    'venue' : IDL.Text,
    'homeTeam' : IDL.Text,
    'sport' : Sport,
    'homeScore' : IDL.Nat,
    'awayTeam' : IDL.Text,
    'awayScore' : IDL.Nat,
    'matchDate' : Time,
  });
  const NewsArticle = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishedAt' : Time,
    'author' : IDL.Text,
    'sport' : Sport,
    'imageUrl' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'notificationType' : IDL.Text,
    'createdAt' : Time,
    'sport' : Sport,
    'matchId' : IDL.Text,
    'message' : IDL.Text,
  });
  const PlayerStats = IDL.Record({
    'recentForm' : IDL.Vec(IDL.Nat),
    'average' : IDL.Float64,
    'matchesPlayed' : IDL.Nat,
    'runsGoalsPoints' : IDL.Nat,
  });
  const Player = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'team' : IDL.Text,
    'sport' : Sport,
    'stats' : PlayerStats,
    'imageUrl' : IDL.Text,
    'position' : IDL.Text,
  });
  const PredictionConfidence = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const MatchPrediction = IDL.Record({
    'keyFactors' : IDL.Text,
    'predictedScore' : IDL.Text,
    'matchId' : IDL.Text,
    'awayWinProbability' : IDL.Nat,
    'confidence' : PredictionConfidence,
    'homeWinProbability' : IDL.Nat,
    'drawProbability' : IDL.Nat,
  });
  const MatchSummary = IDL.Record({
    'generatedAt' : Time,
    'highlights' : IDL.Vec(IDL.Text),
    'summary' : IDL.Text,
    'matchId' : IDL.Text,
    'keyMoments' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'favoriteSport' : IDL.Opt(Sport),
    'name' : IDL.Text,
    'favoriteTeam' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFantasySuggestion' : IDL.Func([FantasySuggestion], [], []),
    'createMatch' : IDL.Func([Match], [], []),
    'createNews' : IDL.Func([NewsArticle], [], []),
    'createNotification' : IDL.Func([Notification], [], []),
    'createPlayer' : IDL.Func([Player], [], []),
    'createPrediction' : IDL.Func([MatchPrediction], [], []),
    'createSummary' : IDL.Func([MatchSummary], [], []),
    'deleteMatch' : IDL.Func([IDL.Text], [], []),
    'deleteNews' : IDL.Func([IDL.Text], [], []),
    'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getAllNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFantasySuggestionByMatchId' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FantasySuggestion)],
        ['query'],
      ),
    'getMatchesBySport' : IDL.Func([Sport], [IDL.Vec(Match)], ['query']),
    'getMatchesByStatus' : IDL.Func([MatchStatus], [IDL.Vec(Match)], ['query']),
    'getNewsBySport' : IDL.Func([Sport], [IDL.Vec(NewsArticle)], ['query']),
    'getPlayersBySport' : IDL.Func([Sport], [IDL.Vec(Player)], ['query']),
    'getPredictionByMatchId' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MatchPrediction)],
        ['query'],
      ),
    'getRecentNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getSummaryByMatchId' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MatchSummary)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateFantasySuggestion' : IDL.Func([FantasySuggestion], [], []),
    'updateMatch' : IDL.Func([Match], [], []),
    'updateNews' : IDL.Func([NewsArticle], [], []),
    'updatePlayer' : IDL.Func([Player], [], []),
    'updatePrediction' : IDL.Func([MatchPrediction], [], []),
    'updateSummary' : IDL.Func([MatchSummary], [], []),
  });
};

export const init = ({ IDL }) => { return []; };