/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: string;
    name: string;
    team: string;
    sport: Sport;
    stats: PlayerStats;
    imageUrl: string;
    position: string;
}
export interface MatchSummary {
    generatedAt: Time;
    highlights: Array<string>;
    summary: string;
    matchId: string;
    keyMoments: string;
}
export interface FantasySuggestion {
    captainName: string;
    viceCaptainId: string;
    reasoning: string;
    viceCaptainName: string;
    matchId: string;
    totalCredits: bigint;
    suggestedPlayers: Array<[string, string]>;
    captainId: string;
}
export type Time = bigint;
export interface Match {
    id: string;
    status: MatchStatus;
    venue: string;
    homeTeam: string;
    sport: Sport;
    homeScore: bigint;
    awayTeam: string;
    awayScore: bigint;
    matchDate: Time;
}
export interface MatchPrediction {
    keyFactors: string;
    predictedScore: string;
    matchId: string;
    awayWinProbability: bigint;
    confidence: PredictionConfidence;
    homeWinProbability: bigint;
    drawProbability: bigint;
}
export interface Notification {
    id: string;
    title: string;
    notificationType: string;
    createdAt: Time;
    sport: Sport;
    matchId: string;
    message: string;
}
export interface NewsArticle {
    id: string;
    title: string;
    content: string;
    publishedAt: Time;
    author: string;
    sport: Sport;
    imageUrl: string;
}
export interface UserProfile {
    favoriteSport?: Sport;
    name: string;
    favoriteTeam?: string;
}
export interface PlayerStats {
    recentForm: Array<bigint>;
    average: number;
    matchesPlayed: bigint;
    runsGoalsPoints: bigint;
}
export enum MatchStatus {
    upcoming = "upcoming",
    live = "live",
    completed = "completed"
}
export enum PredictionConfidence {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum Sport {
    basketball = "basketball",
    football = "football",
    cricket = "cricket",
    tennis = "tennis",
    kabaddi = "kabaddi"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createFantasySuggestion(suggestion: FantasySuggestion): Promise<void>;
    createMatch(match: Match): Promise<void>;
    createNews(article: NewsArticle): Promise<void>;
    createNotification(notification: Notification): Promise<void>;
    createPlayer(player: Player): Promise<void>;
    createPrediction(prediction: MatchPrediction): Promise<void>;
    createSummary(summary: MatchSummary): Promise<void>;
    deleteMatch(id: string): Promise<void>;
    deleteNews(id: string): Promise<void>;
    getAllMatches(): Promise<Array<Match>>;
    getAllNews(): Promise<Array<NewsArticle>>;
    getAllPlayers(): Promise<Array<Player>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFantasySuggestionByMatchId(matchId: string): Promise<FantasySuggestion | null>;
    getMatchesBySport(sport: Sport): Promise<Array<Match>>;
    getMatchesByStatus(status: MatchStatus): Promise<Array<Match>>;
    getNewsBySport(sport: Sport): Promise<Array<NewsArticle>>;
    getPlayersBySport(sport: Sport): Promise<Array<Player>>;
    getPredictionByMatchId(matchId: string): Promise<MatchPrediction | null>;
    getRecentNotifications(): Promise<Array<Notification>>;
    getSummaryByMatchId(matchId: string): Promise<MatchSummary | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateFantasySuggestion(suggestion: FantasySuggestion): Promise<void>;
    updateMatch(match: Match): Promise<void>;
    updateNews(article: NewsArticle): Promise<void>;
    updatePlayer(player: Player): Promise<void>;
    updatePrediction(prediction: MatchPrediction): Promise<void>;
    updateSummary(summary: MatchSummary): Promise<void>;
}
import type { FantasySuggestion as _FantasySuggestion, Match as _Match, MatchPrediction as _MatchPrediction, MatchStatus as _MatchStatus, MatchSummary as _MatchSummary, NewsArticle as _NewsArticle, Notification as _Notification, Player as _Player, PlayerStats as _PlayerStats, PredictionConfidence as _PredictionConfidence, Sport as _Sport, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createFantasySuggestion(arg0: FantasySuggestion): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createFantasySuggestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFantasySuggestion(arg0);
            return result;
        }
    }
    async createMatch(arg0: Match): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(to_candid_Match_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(to_candid_Match_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createNews(arg0: NewsArticle): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createNews(to_candid_NewsArticle_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNews(to_candid_NewsArticle_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createNotification(arg0: Notification): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(to_candid_Notification_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(to_candid_Notification_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPlayer(arg0: Player): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlayer(to_candid_Player_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlayer(to_candid_Player_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPrediction(arg0: MatchPrediction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPrediction(to_candid_MatchPrediction_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPrediction(to_candid_MatchPrediction_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSummary(arg0: MatchSummary): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSummary(arg0);
            return result;
        }
    }
    async deleteMatch(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMatch(arg0);
            return result;
        }
    }
    async deleteNews(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNews(arg0);
            return result;
        }
    }
    async getAllMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatches();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatches();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNews(): Promise<Array<NewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNews();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNews();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPlayers(): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayers();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayers();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFantasySuggestionByMatchId(arg0: string): Promise<FantasySuggestion | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFantasySuggestionByMatchId(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFantasySuggestionByMatchId(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchesBySport(arg0: Sport): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchesBySport(to_candid_Sport_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchesBySport(to_candid_Sport_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchesByStatus(arg0: MatchStatus): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchesByStatus(to_candid_MatchStatus_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchesByStatus(to_candid_MatchStatus_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsBySport(arg0: Sport): Promise<Array<NewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsBySport(to_candid_Sport_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsBySport(to_candid_Sport_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayersBySport(arg0: Sport): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayersBySport(to_candid_Sport_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayersBySport(to_candid_Sport_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPredictionByMatchId(arg0: string): Promise<MatchPrediction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPredictionByMatchId(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPredictionByMatchId(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentNotifications();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentNotifications();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSummaryByMatchId(arg0: string): Promise<MatchSummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSummaryByMatchId(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSummaryByMatchId(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateFantasySuggestion(arg0: FantasySuggestion): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFantasySuggestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFantasySuggestion(arg0);
            return result;
        }
    }
    async updateMatch(arg0: Match): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMatch(to_candid_Match_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMatch(to_candid_Match_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateNews(arg0: NewsArticle): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNews(to_candid_NewsArticle_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNews(to_candid_NewsArticle_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePlayer(arg0: Player): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayer(to_candid_Player_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayer(to_candid_Player_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePrediction(arg0: MatchPrediction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrediction(to_candid_MatchPrediction_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrediction(to_candid_MatchPrediction_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSummary(arg0: MatchSummary): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSummary(arg0);
            return result;
        }
    }
}
function from_candid_MatchPrediction_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchPrediction): MatchPrediction {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_NewsArticle_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsArticle): NewsArticle {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_PredictionConfidence_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PredictionConfidence): PredictionConfidence {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Sport_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sport): Sport {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Sport]): Sport | null {
    return value.length === 0 ? null : from_candid_Sport_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FantasySuggestion]): FantasySuggestion | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MatchPrediction]): MatchPrediction | null {
    return value.length === 0 ? null : from_candid_MatchPrediction_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MatchSummary]): MatchSummary | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _MatchStatus;
    venue: string;
    homeTeam: string;
    sport: _Sport;
    homeScore: bigint;
    awayTeam: string;
    awayScore: bigint;
    matchDate: _Time;
}): {
    id: string;
    status: MatchStatus;
    venue: string;
    homeTeam: string;
    sport: Sport;
    homeScore: bigint;
    awayTeam: string;
    awayScore: bigint;
    matchDate: Time;
} {
    return {
        id: value.id,
        status: from_candid_MatchStatus_n22(_uploadFile, _downloadFile, value.status),
        venue: value.venue,
        homeTeam: value.homeTeam,
        sport: from_candid_Sport_n24(_uploadFile, _downloadFile, value.sport),
        homeScore: value.homeScore,
        awayTeam: value.awayTeam,
        awayScore: value.awayScore,
        matchDate: value.matchDate
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    publishedAt: _Time;
    author: string;
    sport: _Sport;
    imageUrl: string;
}): {
    id: string;
    title: string;
    content: string;
    publishedAt: Time;
    author: string;
    sport: Sport;
    imageUrl: string;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        publishedAt: value.publishedAt,
        author: value.author,
        sport: from_candid_Sport_n24(_uploadFile, _downloadFile, value.sport),
        imageUrl: value.imageUrl
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    team: string;
    sport: _Sport;
    stats: _PlayerStats;
    imageUrl: string;
    position: string;
}): {
    id: string;
    name: string;
    team: string;
    sport: Sport;
    stats: PlayerStats;
    imageUrl: string;
    position: string;
} {
    return {
        id: value.id,
        name: value.name,
        team: value.team,
        sport: from_candid_Sport_n24(_uploadFile, _downloadFile, value.sport),
        stats: value.stats,
        imageUrl: value.imageUrl,
        position: value.position
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    favoriteSport: [] | [_Sport];
    name: string;
    favoriteTeam: [] | [string];
}): {
    favoriteSport?: Sport;
    name: string;
    favoriteTeam?: string;
} {
    return {
        favoriteSport: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.favoriteSport)),
        name: value.name,
        favoriteTeam: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.favoriteTeam))
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    keyFactors: string;
    predictedScore: string;
    matchId: string;
    awayWinProbability: bigint;
    confidence: _PredictionConfidence;
    homeWinProbability: bigint;
    drawProbability: bigint;
}): {
    keyFactors: string;
    predictedScore: string;
    matchId: string;
    awayWinProbability: bigint;
    confidence: PredictionConfidence;
    homeWinProbability: bigint;
    drawProbability: bigint;
} {
    return {
        keyFactors: value.keyFactors,
        predictedScore: value.predictedScore,
        matchId: value.matchId,
        awayWinProbability: value.awayWinProbability,
        confidence: from_candid_PredictionConfidence_n43(_uploadFile, _downloadFile, value.confidence),
        homeWinProbability: value.homeWinProbability,
        drawProbability: value.drawProbability
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    notificationType: string;
    createdAt: _Time;
    sport: _Sport;
    matchId: string;
    message: string;
}): {
    id: string;
    title: string;
    notificationType: string;
    createdAt: Time;
    sport: Sport;
    matchId: string;
    message: string;
} {
    return {
        id: value.id,
        title: value.title,
        notificationType: value.notificationType,
        createdAt: value.createdAt,
        sport: from_candid_Sport_n24(_uploadFile, _downloadFile, value.sport),
        matchId: value.matchId,
        message: value.message
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    live: null;
} | {
    completed: null;
}): MatchStatus {
    return "upcoming" in value ? MatchStatus.upcoming : "live" in value ? MatchStatus.live : "completed" in value ? MatchStatus.completed : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    basketball: null;
} | {
    football: null;
} | {
    cricket: null;
} | {
    tennis: null;
} | {
    kabaddi: null;
}): Sport {
    return "basketball" in value ? Sport.basketball : "football" in value ? Sport.football : "cricket" in value ? Sport.cricket : "tennis" in value ? Sport.tennis : "kabaddi" in value ? Sport.kabaddi : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): PredictionConfidence {
    return "low" in value ? PredictionConfidence.low : "high" in value ? PredictionConfidence.high : "medium" in value ? PredictionConfidence.medium : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NewsArticle>): Array<NewsArticle> {
    return value.map((x)=>from_candid_NewsArticle_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n46(_uploadFile, _downloadFile, x));
}
function to_candid_MatchPrediction_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchPrediction): _MatchPrediction {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_MatchStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchStatus): _MatchStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Match_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Match): _Match {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_NewsArticle_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsArticle): _NewsArticle {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Notification_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Notification): _Notification {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Player_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Player): _Player {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_PredictionConfidence_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PredictionConfidence): _PredictionConfidence {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_Sport_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sport): _Sport {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    publishedAt: Time;
    author: string;
    sport: Sport;
    imageUrl: string;
}): {
    id: string;
    title: string;
    content: string;
    publishedAt: _Time;
    author: string;
    sport: _Sport;
    imageUrl: string;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        publishedAt: value.publishedAt,
        author: value.author,
        sport: to_candid_Sport_n7(_uploadFile, _downloadFile, value.sport),
        imageUrl: value.imageUrl
    };
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    notificationType: string;
    createdAt: Time;
    sport: Sport;
    matchId: string;
    message: string;
}): {
    id: string;
    title: string;
    notificationType: string;
    createdAt: _Time;
    sport: _Sport;
    matchId: string;
    message: string;
} {
    return {
        id: value.id,
        title: value.title,
        notificationType: value.notificationType,
        createdAt: value.createdAt,
        sport: to_candid_Sport_n7(_uploadFile, _downloadFile, value.sport),
        matchId: value.matchId,
        message: value.message
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    team: string;
    sport: Sport;
    stats: PlayerStats;
    imageUrl: string;
    position: string;
}): {
    id: string;
    name: string;
    team: string;
    sport: _Sport;
    stats: _PlayerStats;
    imageUrl: string;
    position: string;
} {
    return {
        id: value.id,
        name: value.name,
        team: value.team,
        sport: to_candid_Sport_n7(_uploadFile, _downloadFile, value.sport),
        stats: value.stats,
        imageUrl: value.imageUrl,
        position: value.position
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    keyFactors: string;
    predictedScore: string;
    matchId: string;
    awayWinProbability: bigint;
    confidence: PredictionConfidence;
    homeWinProbability: bigint;
    drawProbability: bigint;
}): {
    keyFactors: string;
    predictedScore: string;
    matchId: string;
    awayWinProbability: bigint;
    confidence: _PredictionConfidence;
    homeWinProbability: bigint;
    drawProbability: bigint;
} {
    return {
        keyFactors: value.keyFactors,
        predictedScore: value.predictedScore,
        matchId: value.matchId,
        awayWinProbability: value.awayWinProbability,
        confidence: to_candid_PredictionConfidence_n17(_uploadFile, _downloadFile, value.confidence),
        homeWinProbability: value.homeWinProbability,
        drawProbability: value.drawProbability
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: MatchStatus;
    venue: string;
    homeTeam: string;
    sport: Sport;
    homeScore: bigint;
    awayTeam: string;
    awayScore: bigint;
    matchDate: Time;
}): {
    id: string;
    status: _MatchStatus;
    venue: string;
    homeTeam: string;
    sport: _Sport;
    homeScore: bigint;
    awayTeam: string;
    awayScore: bigint;
    matchDate: _Time;
} {
    return {
        id: value.id,
        status: to_candid_MatchStatus_n5(_uploadFile, _downloadFile, value.status),
        venue: value.venue,
        homeTeam: value.homeTeam,
        sport: to_candid_Sport_n7(_uploadFile, _downloadFile, value.sport),
        homeScore: value.homeScore,
        awayTeam: value.awayTeam,
        awayScore: value.awayScore,
        matchDate: value.matchDate
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    favoriteSport?: Sport;
    name: string;
    favoriteTeam?: string;
}): {
    favoriteSport: [] | [_Sport];
    name: string;
    favoriteTeam: [] | [string];
} {
    return {
        favoriteSport: value.favoriteSport ? candid_some(to_candid_Sport_n7(_uploadFile, _downloadFile, value.favoriteSport)) : candid_none(),
        name: value.name,
        favoriteTeam: value.favoriteTeam ? candid_some(value.favoriteTeam) : candid_none()
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PredictionConfidence): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == PredictionConfidence.low ? {
        low: null
    } : value == PredictionConfidence.high ? {
        high: null
    } : value == PredictionConfidence.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchStatus): {
    upcoming: null;
} | {
    live: null;
} | {
    completed: null;
} {
    return value == MatchStatus.upcoming ? {
        upcoming: null
    } : value == MatchStatus.live ? {
        live: null
    } : value == MatchStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sport): {
    basketball: null;
} | {
    football: null;
} | {
    cricket: null;
} | {
    tennis: null;
} | {
    kabaddi: null;
} {
    return value == Sport.basketball ? {
        basketball: null
    } : value == Sport.football ? {
        football: null
    } : value == Sport.cricket ? {
        cricket: null
    } : value == Sport.tennis ? {
        tennis: null
    } : value == Sport.kabaddi ? {
        kabaddi: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
